- Source/Arithmetic.swift
I made the arithmetic operators in Arithmetic.swift `public` so that they can be accessed outside of the framework itself. If the decision to keep these operators non-public was intentional, I'd be interested to learn about why/how. Thanks!
> Public arithmetic operators

- Source/Matrix.swift
This fixes an error on a stale branch that added eigenvalue decomposition to Matrix.swift. The initial call to dgeev_ to obtain the optimal workspace size was not actually used for the subsequent call to dgeev_ for the actual decomposition.
> Fix error in specification of workspace size in call to dgeev_

- Sources/Surge/Arithmetic.swift
- Sources/Surge/Matrix.swift
- Sources/Surge/Statistics.swift
As suggested in #58, all element-wise operations on array changed from `+`-style to `.+`-style.
List of changed operators:
* `+` –> `.+`
* `+=` –> `.+=`
* `-` –> `.-`
* `-=` –> `.-=`
* `/` –> `./`
* `/=` –> `./=`
* `*` –> `.*`
* `*=` –> `.*=`
* `%` –> `.%`
* `%=` –> `.%=`
> Changed element-wise operators from + to .+ to resolve #58

- README.md
As the README already contains a badge indicating Carthage compatibility, it makes sense to also indicate that the library can be consumed via CocoaPods or Swift Package Manager.
> Add README badges indicating CocoaPods and SPM compatibility

- Sources/Surge/Arithmetic.swift
With this PR operators now are strictly forwarding functions.
Once https://github.com/mattt/Surge/pull/105 is merged I'll do a rebase and add unit tests for the remaining `inout`/`…inPlace` functions.
> Added missing explicitly named operator equivalents

- Sources/Surge/Matrix.swift
- Tests/SurgeTests/MatrixTests.swift
Diagonal/eye/identity patterns are common enough for matrix initialization to have them as dedicated initializers.
Depends on https://github.com/mattt/Surge/pull/108
> Added Matrix initializers for common diagonal/eye/identity patterns

- Sources/Surge/Logarithm/Logarithm.swift
- Surge.xcodeproj/project.pbxproj
- Tests/SurgeTests/LogarithmTests.swift
Similar to #119 this PR adds `…InPlace` variants for existing functions, turning the latter into thin wrappers around the former. As such most comments from #119 also apply to this one.
It also adds unit tests, which were completely missing before.
> In-place all the things! (Logarithm Edition)

- Sources/Surge/Arithmetic/Arithmetic.swift
- Sources/Surge/Linear Algebra/Scalar.swift
- Sources/Surge/Linear Algebra/Vector.swift
- Tests/SurgeTests/ArithmeticTests.swift
- Tests/SurgeTests/VectorTests.swift
Similar to #119 this PR adds `…InPlace` variants for existing functions on `Vector<Scalar>`, turning the latter into thin wrappers around the former. As such most comments from #119 also apply to this one.
Depends on #123
> In-place all the things! (Vector Edition)

- Sources/Surge/Linear Algebra/Matrix.swift
- Tests/SurgeTests/ArithmeticTests.swift
- Tests/SurgeTests/VectorTests.swift
- Tests/SurgeTests/XCTAssert+Surge.swift
Vector's operations shallowly wrap those from "Arithmetic", so there's really no point in benchmarking them, when we already have benchmarks in place for the latter.
Vector tests now also moved from explicit `expected` values via literals to ad-hoc un-optimized calculations of the operation.
> Improved vector tests; removed redundant benchmarks

- Sources/Surge/Linear Algebra/Matrix.swift
Hi @loufranco, you added the following struct to Surge in https://github.com/mattt/Surge/pull/95 (https://github.com/mattt/Surge/commit/a6dd5f622ed5f36c74ead2dc54329a2d8f39f855), earlier this year, along with the corresponding eigen-decomposition logic to go with it:
```swift
public struct MatrixEigenDecompositionResult<Scalar> where Scalar: FloatingPoint, Scalar: ExpressibleByFloatLiteral {
let eigenValues: [(Scalar, Scalar)]
let leftEigenVectors: [[(Scalar, Scalar)]]
let rightEigenVectors: [[(Scalar, Scalar)]]
// ...
}
```
From this [issue](https://github.com/mattt/Surge/issues/131) it seems that the members of said type are inaccessible when accessed from a third-party module, due to being implicitly marked as `internal`.
So I was wondering if you could tell me if I'd be right to …
> Fix member access-levels of `MatrixEigenDecompositionResult<Scalar>`

- Sources/Surge/Linear Algebra/Matrix.swift
- Sources/Surge/Linear Algebra/Vector.swift
- Tests/SurgeTests/MatrixTests.swift
- Tests/SurgeTests/VectorTests.swift
Addresses https://github.com/mattt/Surge/issues/85
> Added closure-based initializers for `Matrix` & `Vector` and corresponding unit test

- .travis.yml
It currently takes ~4min alone, just to run `brew  update` on Travis-CI.  
Let's see if caching gets it down a bit.
> Added caching for Homebrew

- Sources/Surge/Arithmetic/Arithmetic.swift
- Tests/SurgeTests/ArithmeticTests.swift
… to the more appropriate `elmodInPlace`.
This is a non-breaking change, due to use of `internal`.
> Renamed `internal`-scoped `func modInPlace([_], [_])`

- Sources/Surge/Linear Algebra/Matrix.swift
A very common thing to check for with matrices, so it makes sense to provide such info in an easily accessible way.
> Added `var shape: Shape` to `Matrix<Scalar>`

- .swiftlint.yml
- Sources/Surge/Arithmetic/Arithmetic.swift
- Sources/Surge/Linear Algebra/Matrix.swift
- Sources/Surge/Linear Algebra/Scalar.swift
- Sources/Surge/Linear Algebra/Vector.swift
- Sources/Surge/Random/Random.swift
- Sources/Surge/Statistics/Random.swift
- Surge.xcodeproj/project.pbxproj
- Tests/SurgeTests/MatrixTests.swift
- Tests/SurgeTests/RandomTests.swift
As this is a purely additive change I figured we actually don't need to wait for a v3.x.  
We have plenty of stuff on our plate for that already.
Resolves https://github.com/Jounce/Surge/issues/144
> Added functions for generating uniform/normal distributed randomness

- Sources/Surge/Linear Algebra/Matrix.swift
- Sources/Surge/Linear Algebra/Scalar.swift
- Sources/Surge/Linear Algebra/Vector.swift
- Sources/Surge/Random/Random.swift
I realized that using `mu` & `sigma`, as commonly used in mathematical formulas is an inferior choice of labels.
Basically everybody who knows `mu`/`sigma` understands that they stand for `mean`/`stdDeviation`.
The inverse however is not necessarily true, so we should stick with the more widely  understandable names, I think.
> Replaced `mu`/`sigma` with the more descriptive `mean`/`stdDeviation`

- README.md
- Surge.playground/Contents.swift
The example in README and playground should update for renaming `mul` to `elmul`.
> Update usage of `mul` in README and playground should to `elmul`.

- Sources/Surge/Auxiliary Functions/Auxiliary.swift
'ceil' and 'floor' were calling the same function internally, and both were working as ceil.
> Fix floor function

- Sources/Surge/Linear Algebra/Matrix.swift
The current version relies on Foundation and does not need to. This PR removes that dependancy, which allows the resulting package to be used in a project using watchOS.
> Remove Dependance on Foundation NSString

- Sources/Surge/Random/Random.swift
- Sources/Surge/Utilities/Array+Extensions.swift
- Sources/Surge/Utilities/ArraySlice+Extensions.swift
- Sources/Surge/Utilities/OperatorPrecedences.swift
- Sources/Surge/Utilities/UnsafeMemory.swift
- Sources/Surge/Utilities/UnsafeMutableMemory.swift
- Tests/SurgeBenchmarkTests/ArithmeticTests.swift
- Tests/SurgeBenchmarkTests/LogarithmTests.swift
- Tests/SurgeBenchmarkTests/SurgeBenchmarkTests+Extensions.swift
- Tests/SurgeBenchmarkTests/TrigonometricTests.swift
- Tests/SurgeTests/ArithmeticTests.swift
- Tests/SurgeTests/AuxiliaryTests.swift
- Tests/SurgeTests/ConvolutionTests.swift
- Tests/SurgeTests/LogarithmTests.swift
- Tests/SurgeTests/RandomTests.swift
- Tests/SurgeTests/StatisticsTests.swift
- Tests/SurgeTests/SurgeTests+Extensions.swift
- Tests/SurgeTests/TrigonometricTests.swift
- Tests/SurgeTests/XCTAssert+Surge.swift
Following up on #177, we should be able to remove most if not all of the existing imports of the Foundation framework.
> Remove unnecessary imports of Foundation framework
