Jounce/Surge

Source/Matrix.swift
This, in my opinion, makes Matrices much nicer to work with, especially since the number of rows and columns only have internal access.
=> Add SequenceType extension to Matrix

Surge.playground/section-1.swift
* Apply new Playground plotting API.
* Apply new map generating style.
=> Fix for Xcode 7.2 and Swift 2.1.1

Source/Matrix.swift
Adding right division to Matrix. `A/B = A * B^(-1)`
=> Add division to Matrix

Source/Arithmetic.swift, Source/Matrix.swift
* Fix division that it should be using `inv` instead of operator `′` which is doing transpose.
* Add a method to calculate distance between two vectors. This could be useful for some machine learning algorithm.
=> Fix division and add dist method 

Source/Arithmetic.swift
Thanks for a great framework; I have been using it for a while now! I checked out a new copy this evening and noticed that it was failing to build because dist() was calling subtraction on [Float] and [Double] types without subtraction existing for these types. These have been implemented and included below.
1) Added sub() public function to implement subtraction on float and double
2) Added support for '-' operator using sub()
3) Resolved compile error in dist()
=> Implementation of subtraction and fixed dist() build error

README.md, Source/Arithmetic.swift, Source/Convolution.swift, Surge.xcodeproj/project.pbxproj, Tests/ConvolutionTests.swift, Tests/XCTestCase+Surge.swift
Hey again! I've made some developments to Surge that I think might be beneficial to the framework.
1. Implemented convolution with `vDSP_conv()` for float and doubles
2. Implemented cross-correlation with `vDSP_conv()` for float and doubles
3. Implemented auto-correlation with `vDSP_conv()` for float and doubles
4. All functions have been tested against the corresponding MATLAB implementation and I implemented a test suite for all 6 functions (using test data from MATLAB)
5. Implemented an `XCTestCase` for checking array equality with accuracy for float and doubles
6. Adjusted README.md to show inclusion of `sub`, `conv` and `xcorr` in the framework
Let me know if you would like me to make any changes to the code before you accept this PR!
=> Convolution + Cross-Correlation + Autocorrelation

Source/Matrix.swift, Source/Power.swift, Surge.xcodeproj/project.pbxproj, Tests/MatrixTests.swift, Tests/PowerTests.swift
* `Matrix` confirms to `Equatable`
* Add `subscript` supports return specific rows or columns
* Add support for scaling matrix by row or by column.
* Make `pow` supports applying to every elements in vector.
=> Add some support methods for `Matrix`

Source/Arithmetic.swift
Adding sum of square values. Using Accelerate framework.
There is compute dist methods. May also use Accelerate :)
Thanks a lot for your nice & clean framework.
=> Adding sum of square values.

.travis.yml, Metadata/Info-Tests.plist, Metadata/Info-macOS.plist, Metadata/Info.plist, Surge.podspec, Surge.xcodeproj/project.pbxproj, Surge.xcodeproj/xcshareddata/xcschemes/Surge-iOS.xcscheme, Surge.xcodeproj/xcshareddata/xcschemes/Surge-macOS.xcscheme, Surge.xcodeproj/xcshareddata/xcschemes/Surge-tvOS.xcscheme, Surge.xcodeproj/xcshareddata/xcschemes/Surge-watchOS.xcscheme, Tests/SurgeTests/ConvolutionTests.swift
Also update the podspec to specify support for tvOS and watchOS
=> Add macOS, tvOS and watchOS targets

Sources/Surge/Matrix.swift
* Matrix initialization from flat grid
* Added methods for single row and column initialization
* Changed raw matrix initialization to sequence to allow Matrix creation without redundant Array creation and copying (i.e. when using repeatedValue as initializer)
* Added Matrix<Float> sum method (only Matrix<Double> was present)
* Added Matrix + Scalar operator for Double and Float matrices
=> Optimized performance of Matrix initialization and added a few operations

.travis.yml
=> Run SwiftLint in CI

Tests/SurgeTests/MatrixTests.swift, Tests/SurgeTests/VectorTests.swift
Depends on https://github.com/mattt/Surge/pull/104
=> Added unit tests for matrix arithmetic

Tests/SurgeTests/ArithmeticTests.swift
Depends on https://github.com/mattt/Surge/pull/104.
=> Added unit tests & benchmarks for several arithmetic functions

Sources/Surge/Arithmetic/Arithmetic.swift, Sources/Surge/Linear Algebra/Matrix.swift, Sources/Surge/Linear Algebra/Vector.swift
=> Convenience helper functions for wrapping `…InPlace` functions

.travis.yml, Surge.xcodeproj/xcshareddata/xcschemes/SurgeBenchmarkTests-macOS.xcscheme, Tests/SurgeBenchmarkTests/ArithmeticTests.swift
While we don't want to run benchmarks on CI we certainly want to ensure they build properly. 🤦🏻‍♂️
=> Fix benchmarks

README.md, Sources/Surge/Statistics/Statistics.swift, Surge.xcodeproj/project.pbxproj, Tests/SurgeTests/ArithmeticTests.swift, Tests/SurgeTests/StatisticsTests.swift
Added missing `func variance` to 'Statistics.swift' and added corresponding (and until now still missing) unit tests: 'StatisticsTests.swift'.
=> Statistics improvements

Sources/Surge/Auxiliary Functions/Auxiliary.swift, Tests/SurgeBenchmarkTests/ArithmeticTests.swift, Tests/SurgeBenchmarkTests/SurgeBenchmarkTests+Extensions.swift, Tests/SurgeTests/AuxiliaryTests.swift, Tests/SurgeTests/SurgeTests+Extensions.swift, Tests/SurgeTests/TrigonometricTests.swift
… and corresponding unit tests.
I somehow seem to have missed this file during my recent refactors. 🤷‍♂
=> Added `…InPlace` variants for functions in ‘Auxiliary.swift’

Tests/SurgeBenchmarkTests/ArithmeticTests.swift
Weird. I could have sworn I already fixed this.  
Must have messed up a rebase, I guess. 😇
=> Fixed unit tests

.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
Context: https://github.com/apple/swift-package-manager/pull/2209
=> Added '.swiftpm' to tracked git files

.github/workflows/ci.yml
Fixes what appears to be [an erroneous CI failure](https://github.com/Jounce/Surge/runs/1625345511?check_suite_focus=true) for #172.
=> Fix lint job in CI workflow

.github/workflows/ci.yml
=> Name CI Jobs

.github/workflows/ci.yml, .github/workflows/release.yml, Surge.podspec
This PR adds a GitHub Actions workflow to automatically push to CocoaPods Trunk when a new version is tagged.
=> Add release automation
